version: "3.8"

services:
  customerservice:
    container_name: customerservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - customerdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customerdb:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop
      - SPRING_JPA_HIBERNATE_SHOW-SQL=true

  customerdb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=customerdb